//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KolkoKrzyzyk.ServiceKolkoKrzyzyk {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk")]
    public interface IGraKolkoKrzyzyk {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/Start", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/StartResponse")]
        void Start();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/Start", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/StartResponse")]
        System.Threading.Tasks.Task StartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/WykonajRuch", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/WykonajRuchResponse")]
        KolkoKrzyzyk.ServiceKolkoKrzyzyk.WykonajRuchResponse WykonajRuch(KolkoKrzyzyk.ServiceKolkoKrzyzyk.WykonajRuchRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ operacja ma wiele wartości zwracanych.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/WykonajRuch", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/WykonajRuchResponse")]
        System.Threading.Tasks.Task<KolkoKrzyzyk.ServiceKolkoKrzyzyk.WykonajRuchResponse> WykonajRuchAsync(KolkoKrzyzyk.ServiceKolkoKrzyzyk.WykonajRuchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/SparwdzWygrana", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/SparwdzWygranaResponse")]
        int SparwdzWygrana(int wiersz, int kolumna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraKolkoKrzyzyk/SparwdzWygrana", ReplyAction="http://tempuri.org/IGraKolkoKrzyzyk/SparwdzWygranaResponse")]
        System.Threading.Tasks.Task<int> SparwdzWygranaAsync(int wiersz, int kolumna);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WykonajRuch", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WykonajRuchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int wiersz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int kolumna;
        
        public WykonajRuchRequest() {
        }
        
        public WykonajRuchRequest(int wiersz, int kolumna) {
            this.wiersz = wiersz;
            this.kolumna = kolumna;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WykonajRuchResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WykonajRuchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool WykonajRuchResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int wierszServer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int kolumnaServer;
        
        public WykonajRuchResponse() {
        }
        
        public WykonajRuchResponse(bool WykonajRuchResult, int wierszServer, int kolumnaServer) {
            this.WykonajRuchResult = WykonajRuchResult;
            this.wierszServer = wierszServer;
            this.kolumnaServer = kolumnaServer;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGraKolkoKrzyzykChannel : KolkoKrzyzyk.ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GraKolkoKrzyzykClient : System.ServiceModel.ClientBase<KolkoKrzyzyk.ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk>, KolkoKrzyzyk.ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk {
        
        public GraKolkoKrzyzykClient() {
        }
        
        public GraKolkoKrzyzykClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GraKolkoKrzyzykClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraKolkoKrzyzykClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraKolkoKrzyzykClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Start() {
            base.Channel.Start();
        }
        
        public System.Threading.Tasks.Task StartAsync() {
            return base.Channel.StartAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KolkoKrzyzyk.ServiceKolkoKrzyzyk.WykonajRuchResponse KolkoKrzyzyk.ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk.WykonajRuch(KolkoKrzyzyk.ServiceKolkoKrzyzyk.WykonajRuchRequest request) {
            return base.Channel.WykonajRuch(request);
        }
        
        public bool WykonajRuch(int wiersz, int kolumna, out int wierszServer, out int kolumnaServer) {
            KolkoKrzyzyk.ServiceKolkoKrzyzyk.WykonajRuchRequest inValue = new KolkoKrzyzyk.ServiceKolkoKrzyzyk.WykonajRuchRequest();
            inValue.wiersz = wiersz;
            inValue.kolumna = kolumna;
            KolkoKrzyzyk.ServiceKolkoKrzyzyk.WykonajRuchResponse retVal = ((KolkoKrzyzyk.ServiceKolkoKrzyzyk.IGraKolkoKrzyzyk)(this)).WykonajRuch(inValue);
            wierszServer = retVal.wierszServer;
            kolumnaServer = retVal.kolumnaServer;
            return retVal.WykonajRuchResult;
        }
        
        public System.Threading.Tasks.Task<KolkoKrzyzyk.ServiceKolkoKrzyzyk.WykonajRuchResponse> WykonajRuchAsync(KolkoKrzyzyk.ServiceKolkoKrzyzyk.WykonajRuchRequest request) {
            return base.Channel.WykonajRuchAsync(request);
        }
        
        public int SparwdzWygrana(int wiersz, int kolumna) {
            return base.Channel.SparwdzWygrana(wiersz, kolumna);
        }
        
        public System.Threading.Tasks.Task<int> SparwdzWygranaAsync(int wiersz, int kolumna) {
            return base.Channel.SparwdzWygranaAsync(wiersz, kolumna);
        }
    }
}
